package ThreadPractice;

/**
 * Created by kush on 13/09/16.
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * 0+1 =1 , 1+1 =2 ,
 * xn = xn-1 + xn-2
 */
public class Fibonacci_sequence_Question2 {

static int count =0;
    public static void main(String Args[]){

       /*for(int i=0,j=1; i<10 && j<10; i++ ,j++){
           System.out.println("i : "+i+"\t"+"J : "+j + "\t"+ "i+j "+ (i+j));

        }*/

        int fib1 = 0;
        int fib2 = 0;
        int curFib = 1;
        int sum = 0;
        while(curFib < 4000000){

            if(curFib % 2 == 0){
                sum += curFib;
            }
            fib1 = fib2;
            fib2 = curFib;
            curFib = fib1 + fib2;
        }
        System.out.println("Solution to problem 2 = " + sum);

    }




}


